; === charmap.asm
; Character mappings

charmap "A", $01
charmap "B", $02
charmap "C", $03
charmap "D", $04
charmap "E", $05
charmap "F", $06
charmap "G", $07
charmap "H", $08
charmap "I", $09
charmap "J", $0A
charmap "K", $0B
charmap "L", $0C
charmap "M", $0D
charmap "N", $0E
charmap "O", $0F
charmap "P", $10
charmap "Q", $11
charmap "R", $12
charmap "S", $13
charmap "T", $14
charmap "U", $15
charmap "V", $16
charmap "W", $17
charmap "X", $18
charmap "Y", $19
charmap "Z", $1A
charmap "a", $1B
charmap "b", $1C
charmap "c", $1D
charmap "d", $1E
charmap "e", $1F
charmap "f", $20
charmap "g", $21
charmap "h", $22
charmap "i", $23
charmap "j", $24
charmap "k", $25
charmap "l", $26
charmap "m", $27
charmap "n", $28
charmap "o", $29
charmap "p", $2A
charmap "q", $2B
charmap "r", $2C
charmap "s", $2D
charmap "t", $2E
charmap "u", $2F
charmap "v", $30
charmap "w", $31
charmap "x", $32
charmap "y", $33
charmap "z", $34
charmap "!", $35
charmap ",", $36
charmap "?", $37
charmap "\"", $38
charmap "-", $39
charmap ".", $3A
charmap ":", $3B
charmap "(", $3C
charmap ")", $3D
charmap " ", $3E
charmap "_", $3F
charmap "$", $40
charmap "'", $41
charmap "/", $42
charmap "0", $43
charmap "1", $44
charmap "2", $45
charmap "3", $46
charmap "4", $47
charmap "5", $48
charmap "6", $49
charmap "7", $4A
charmap "8", $4B
charmap "9", $4C
charmap "é", $4D
charmap "á", $A8
charmap "ó", $A9
